"""
Vision Specific Events.
"""

from enum import Enum, auto

class VisionEvents(Enum):
    SCREEN_CAPTURED = "SCREEN_CAPTURED"
    OCR_COMPLETED = "OCR_COMPLETED"
    VISION_ANALYZED = "VISION_ANALYZED"
    PDF_PARSED = "PDF_PARSED"
    WINDOW_CAPTURED = "WINDOW_CAPTURED"
    IMAGE_CAPTURED = "IMAGE_CAPTURED"
    REGION_CAPTURED = "REGION_CAPTURED"
    UI_DETECTED = "UI_DETECTED"
