class CapabilityEvents:
    CAPABILITY_INITIALIZED = "CAPABILITY_INITIALIZED"
    CAPABILITY_READY = "CAPABILITY_READY"
    CAPABILITY_EXECUTED = "CAPABILITY_EXECUTED"
    CAPABILITY_FAILED = "CAPABILITY_FAILED"
    CAPABILITY_DISABLED = "CAPABILITY_DISABLED"
    CAPABILITY_SHUTDOWN = "CAPABILITY_SHUTDOWN"
