from enum import Enum

class FilesystemEvent(str, Enum):
    FILE_CREATED = "FILE_CREATED"
    FILE_DELETED = "FILE_DELETED"
    FILE_MOVED = "FILE_MOVED"
    FILE_COPIED = "FILE_COPIED"
    FILE_RENAMED = "FILE_RENAMED"
    
    FOLDER_CREATED = "FOLDER_CREATED"
    FOLDER_DELETED = "FOLDER_DELETED"
    
    ZIP_CREATED = "ZIP_CREATED"
    ZIP_EXTRACTED = "ZIP_EXTRACTED"
    
    SEARCH_COMPLETED = "SEARCH_COMPLETED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    
    # Progress events for UI/Batch ops
    COPY_STARTED = "COPY_STARTED"
    COPY_PROGRESS = "COPY_PROGRESS"
    COPY_COMPLETED = "COPY_COMPLETED"
    
    MOVE_STARTED = "MOVE_STARTED"
    MOVE_COMPLETED = "MOVE_COMPLETED"
    
    ZIP_PROGRESS = "ZIP_PROGRESS"
