import win32con

# Windows ShowWindow Constants
SW_HIDE = win32con.SW_HIDE
SW_SHOWNORMAL = win32con.SW_SHOWNORMAL
SW_SHOWMINIMIZED = win32con.SW_SHOWMINIMIZED
SW_MAXIMIZE = win32con.SW_MAXIMIZE
SW_SHOWMAXIMIZED = win32con.SW_SHOWMAXIMIZED
SW_SHOWNOACTIVATE = win32con.SW_SHOWNOACTIVATE
SW_SHOW = win32con.SW_SHOW
SW_MINIMIZE = win32con.SW_MINIMIZE
SW_SHOWMINNOACTIVE = win32con.SW_SHOWMINNOACTIVE
SW_SHOWNA = win32con.SW_SHOWNA
SW_RESTORE = win32con.SW_RESTORE
SW_SHOWDEFAULT = win32con.SW_SHOWDEFAULT

# Windows Messages
WM_CLOSE = win32con.WM_CLOSE
